### ISSUE TITLE
Device Error: Unexpected RESP Code 255

### ISSUE THREAD

**Issue by EvanLuo42** [canokeys/canokey-web-console#49]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/62578958/207622639-a93a79ff-37bb-41f7-bb82-b16172e2d7ad.png">
Could not load Canokey.

Browser: Chrome 108.0.5359.124
OS&Device: macOS Ventura 13.1 Macbook Pro M1 (arm)

**Comment by liuhaoXD** [comment]
met same issue LOL

**Comment by artefaritaKuniklo** [comment]
might caused by
1. ccid occupied by other process
2. pcscd.service not running

restart the service & disconnect and re-plug in canokey might help
